<Project>
  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>All</AnalysisMode>
    <ArtifactsPath>$(MSBuildThisFileDirectory).artifacts/</ArtifactsPath>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)assets/ratiocinia.snk</AssemblyOriginatorKeyFile>
    <Deterministic>true</Deterministic>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>14</LangVersion>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Nullable>enable</Nullable>
    <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
    <RootNamespace>Ratiocinia</RootNamespace>
    <UseArtifactsOutput>true</UseArtifactsOutput>
  </PropertyGroup>
</Project>
