<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\src\Internal\Ratiocinia.Algorithms.Generic.Internal\RationalOperations.cs">
      <Link>RationalOperations.cs</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ratiocinia.Algorithms.Specialized\Ratiocinia.Algorithms.Specialized.csproj" />
  </ItemGroup>

</Project>
