<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Checked/unchecked arithmetic policy implementations and supporting models for rational arithmetic.</Description>
    <PackageTags>generic-math;implementations;models;rational</PackageTags>
    <Title>Rational arithmetic models</Title>
    <VersionPrefix>0.1.3</VersionPrefix>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyVersion>0.1.3</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <NoWarn Condition="'$(Configuration)' == 'Debug' OR '$(VersionSuffix)' != ''">$(NoWarn);CS1591</NoWarn>
    <RootNamespace>Ratiocinia.Models</RootNamespace>
    <TargetFrameworks>net7.0;net9.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion Condition="'$(TargetFramework)' == 'net9.0'">13</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNet.ReproducibleBuilds" PrivateAssets="All" />
    <PackageReference Include="MathFoundations.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ratiocinia.Algorithms.Generic\Ratiocinia.Algorithms.Generic.csproj" />
    <ProjectReference Include="..\Internal\Ratiocinia.Algorithms.Generic.Internal\Ratiocinia.Algorithms.Generic.Internal.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Tests.Models, PublicKey=0024000004800000140100000602000000240000525341310008000001000100853326D16BE54B574509D7254BCAFA40FB7766118F1D4D80E5DCF5443E9F5F957F8DDA92FC82D01E95CEA3B3CE8866BF25FBC6DFCB22C64B28C3CF76498509CC574EFAD89BE754A64681E0D7ED5A4EE28F402B8C6B6CA35848DC6165E88554DBFF13CE032613088492C5B7C41B676758E186303D716421C4114CEEE4381A5BFD3D00D1E3AB56B07C4C4F53F9D72A8BE23FF4DA5A04F4609D80C2CB61D8C4B0D0013F4EB6583A12CEA139F039A8EC2909D582E19E085E1FF08E1D08C8C8A857A3D3C3D9D647816BBBF1782FB311F865F4B57DD0DE30D0092D99AF538EE4AA422B585EAFE0D4214D0FCE37DEA9E663F1597BB19B36C2B27F7C7D58B3452BEE4DBA</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
