<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Policy-based rational arithmetic algorithms with minimal dependencies.</Description>
    <PackageTags>algorithms;generic-math;rational</PackageTags>
    <Title>Rational arithmetic generic algorithms</Title>
    <VersionPrefix>0.1.3</VersionPrefix>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyVersion>0.1.3</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <NoWarn Condition="'$(Configuration)' == 'Debug' OR '$(VersionSuffix)' != ''">$(NoWarn);CS1591</NoWarn>
    <RootNamespace>Ratiocinia.Algorithms.Generic</RootNamespace>
    <TargetFrameworks>netstandard2.0;net9.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion Condition="'$(TargetFramework)' == 'net9.0'">13</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(DebugType)' == 'portable'">
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <EmbedAllSources>true</EmbedAllSources>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ratiocinia.Abstractions\Ratiocinia.Abstractions.csproj" />
  </ItemGroup>

</Project>
