<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Policy-based rational arithmetic algorithms with minimal dependencies.</Description>
    <PackageTags>algorithms;generic-math;rational</PackageTags>
    <Title>Rational arithmetic generic algorithms</Title>
    <VersionSuffix>preview</VersionSuffix>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyVersion>0.1</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <NoWarn Condition="'$(Configuration)' == 'Debug' OR '$(VersionSuffix)' != ''">$(NoWarn);CS1591</NoWarn>
    <RootNamespace>Ratiocinia.Algorithms.Generic</RootNamespace>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(DebugType)' == 'portable'">
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <EmbedAllSources>true</EmbedAllSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ratiocinia.Abstractions\Ratiocinia.Abstractions.csproj" />
  </ItemGroup>

</Project>
