<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Arbitrary-precision rational arithmetic via BigIntegerRational.</Description>
    <PackageTags>arbitrary-precision;fraction;numeric;rational</PackageTags>
    <Title>BigIntegerRational</Title>
    <VersionSuffix>preview</VersionSuffix>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyVersion>0.1.1</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <NoWarn Condition="'$(Configuration)' == 'Debug' OR '$(VersionSuffix)' != ''">$(NoWarn);CS1591</NoWarn>
    <TargetFrameworks>net7.0;net9.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNet.ReproducibleBuilds" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ratiocinia.Algorithms.Specialized\Ratiocinia.Algorithms.Specialized.csproj" />
    <ProjectReference Include="..\Ratiocinia.Models\Ratiocinia.Models.csproj" />
  </ItemGroup>

</Project>
