<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Convenience wrappers over the core rational algorithms using .NET generic math constraints.</Description>
    <PackageTags>algorithms;generic-math;rational</PackageTags>
    <Title>Rational arithmetic specialized algorithms</Title>
    <VersionPrefix>0.1.3</VersionPrefix>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyVersion>0.1.3</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <NoWarn Condition="'$(Configuration)' == 'Debug' OR '$(VersionSuffix)' != ''">$(NoWarn);CS1591</NoWarn>
    <RootNamespace>Ratiocinia.Algorithms.Specialized</RootNamespace>
    <TargetFrameworks>net7.0;net9.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(DebugType)' == 'portable'">
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <EmbedAllSources>true</EmbedAllSources>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ratiocinia.Algorithms.Generic\Ratiocinia.Algorithms.Generic.csproj" />
    <ProjectReference Include="..\Ratiocinia.Models\Ratiocinia.Models.csproj" />
  </ItemGroup>

</Project>
