<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Convenience wrappers over the core rational algorithms using .NET generic math constraints.</Description>
    <PackageTags>algorithms;generic-math;rational</PackageTags>
    <Title>Rational arithmetic specialized algorithms</Title>
    <VersionSuffix>preview</VersionSuffix>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyVersion>0.1</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <NoWarn Condition="'$(Configuration)' == 'Debug' OR '$(VersionSuffix)' != ''">$(NoWarn);CS1591</NoWarn>
    <RootNamespace>Ratiocinia.Algorithms.Specialized</RootNamespace>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(DebugType)' == 'portable'">
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <EmbedAllSources>true</EmbedAllSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNet.ReproducibleBuilds" PrivateAssets="All" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ratiocinia.Algorithms.Generic\Ratiocinia.Algorithms.Generic.csproj" />
    <ProjectReference Include="..\Ratiocinia.Models\Ratiocinia.Models.csproj" />
  </ItemGroup>

</Project>
