<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionSuffix>preview</VersionSuffix>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyVersion>0.1</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <NoWarn Condition="'$(Configuration)' == 'Debug' OR '$(VersionSuffix)' != ''">$(NoWarn);CS1591</NoWarn>
    <RootNamespace>Ratiocinia.Algorithms.Specialized</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNet.ReproducibleBuilds" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ratiocinia.Abstractions\Ratiocinia.Abstractions.csproj" />
    <ProjectReference Include="..\Ratiocinia.Algorithms.Generic\Ratiocinia.Algorithms.Generic.csproj" />
    <ProjectReference Include="..\Ratiocinia.Models\Ratiocinia.Models.csproj" />
  </ItemGroup>

</Project>
